version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws --version
      - $(aws ecr get-login --region $AWS_DEFAULT_REGION --no-include-email)
      - REPOSITORY_URI_BACKEND=063279173567.dkr.ecr.us-east-1.amazonaws.com/shellhacks_backend
      - REPOSITORY_URI_FRONTEND=063279173567.dkr.ecr.us-east-1.amazonaws.com/shellhacks_frontend
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
      - IMAGE_TAG=${COMMIT_HASH:=latest}
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker images...
      - docker build -t $REPOSITORY_URI_BACKEND:$IMAGE_TAG --target Production ./backend
      - docker build -t $REPOSITORY_URI_FRONTEND:$IMAGE_TAG --target Production ./frontend
      - echo Pushing the Docker images...
      - docker push $REPOSITORY_URI_BACKEND:$IMAGE_TAG
      - docker push $REPOSITORY_URI_FRONTEND:$IMAGE_TAG
      - echo Registering a new ECS task definition...
      - aws ecs register-task-definition --family your-task-definition-family --container-definitions file://container-definitions.json
      - echo Updating the ECS service...
      - aws ecs update-service --service your-service --task-definition your-task-definition-family --cluster your-cluster
  post_build:
    commands:
      - echo Build completed on `date`
