version: "3.9"
services:
  shellhacks:
    container_name: shellhacks
    build:
      context: ./shellhacks
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - ./.env
  backend:
    container_name: backend
    build:
      context: ./backend
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
