version: "3.9"
services:
  shellhacks:
    networks:
      - shell_network
    container_name: shellhacks
    build:
      context: ./shellhacks
      target: Development
    volumes:
      - ./shellhacks/src:/shellhacks/src
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - ./.env
  backend:
    networks:
      - shell_network
    container_name: backend
    build:
      context: ./backend
      target: Development
    volumes:
      - ./backend/src:/backend/src
    ports:
      - ${PORT}:${PORT}
      - 5555:5555
    env_file:
      - ./.env

networks:
  shell_network:
    driver: bridge
