version: "3.9"
services:
  shellhacks:
    build:
      context: ./shellhacks
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    env_file:
      - ./.env
  backend:
    build:
      context: ./backend
    ports:
      - ${PORT}:${PORT}
    env_file:
      - ./.env
  nginx:
    image: nginx:latest
    volumes:
      - "./conf.d/my_conf.conf:/etc/nginx/nginx.conf"
    depends_on:
      - shellhacks
      - backend
    ports:
      - 80:80
