export interface newHackerApplication {
      event_id: number,
      first_name: string,
      last_name: string,
      email: string,
      discord: string,
      gender: string,
      ethnicity: string,
      phone_number: string,
      race: string,
      dob: Date,
      major: string,
      school: string,
      resume_path: string,
      github: string | null | undefined,
      linkedin: string | null | undefined,
      level_of_study: string,
      interest_response: string,
      email_message_status: boolean,
      developer_role: string,
}